services:
  nginx:
    container_name: reverse
    hostname: reverse
    image: nginx:1.27
    restart: unless-stopped
    logging:
      driver: "json-file"
    volumes:
      - ./nginx/data/nginx:/etc/nginx/conf.d
      - ./nginx/data/certbot/conf:/etc/letsencrypt
      - ./nginx/data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    links:
      - rumppy
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./nginx/data/certbot/conf:/etc/letsencrypt
      - ./nginx/data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  rumppy:
    image: rumppy:latest
    container_name: rumppy
    hostname: rummpy
    restart: always
    ports:
    - "8889:8889"